// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPcyiYLuQzc6jWfPoHStd-Pros4HYGEXI',
    appId: '1:628776946173:web:8b20910d975f90500ab194',
    messagingSenderId: '628776946173',
    projectId: 'vit-hostel-app',
    authDomain: 'vit-hostel-app.firebaseapp.com',
    storageBucket: 'vit-hostel-app.appspot.com',
    measurementId: 'G-3L04BVQQXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4jyZ51AdLeVJAaj_0NY-pPH3Vi7ayYbQ',
    appId: '1:628776946173:android:cb5171559f55d2e20ab194',
    messagingSenderId: '628776946173',
    projectId: 'vit-hostel-app',
    storageBucket: 'vit-hostel-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA76XFjBe3W-06YMMb-5c-2uOLkP7VpbQ',
    appId: '1:628776946173:ios:f3bb41120dae76ae0ab194',
    messagingSenderId: '628776946173',
    projectId: 'vit-hostel-app',
    storageBucket: 'vit-hostel-app.appspot.com',
    iosClientId: '628776946173-c01leqn45avban2oam54ua94e2o7l5g0.apps.googleusercontent.com',
    iosBundleId: 'com.example.vitHostelRepo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA76XFjBe3W-06YMMb-5c-2uOLkP7VpbQ',
    appId: '1:628776946173:ios:f3bb41120dae76ae0ab194',
    messagingSenderId: '628776946173',
    projectId: 'vit-hostel-app',
    storageBucket: 'vit-hostel-app.appspot.com',
    iosClientId: '628776946173-c01leqn45avban2oam54ua94e2o7l5g0.apps.googleusercontent.com',
    iosBundleId: 'com.example.vitHostelRepo',
  );
}
